### PR TITLE
Update namespace

### PR DESCRIPTION
**Pull request by aakarshg**

### CODE REVIEW

**Comment by dustinblack** [comment]
It looks like we need to add the namespace to the CR as well.

**Comment by dustinblack** [comment]
Also note for couchbase tests in 'shift in CI we will need to update the RH pull secret file there.

**Comment by dustinblack** [comment]
I'll merge this and then update the CR in my branch since this otherwise looks good. Note the needed CI update after this merges to ripsaw/master, though.

**Comment by aakarshg** [comment]
thanks @dustinblack

**Pull request merged**
